### PR TITLE
Typo: shema => schema

### PR DESCRIPTION
**Pull request by pscheit**
This is a typo right? How can I validate if the schema is correct?

### CODE REVIEW

**Comment by mkjetbrains** [comment]
> This is a typo right? How can I validate if the schema is correct?

Thank you for your feedback! You are right about the typo, but first, we must check if the bundled plugins will work correctly with this typo fixed. We will update the docs afterward.
As to validation, please see the descriptor currently attached to [this issue](https://youtrack.jetbrains.com/issue/TW-9646).

**Comment by VladRassokhin** [comment]
@mkjetbrains they will work. Actually half of bundled plugins have that typo fixed years ago. Safe to merge

**Comment by mkjetbrains** [comment]
@pscheit there is a restriction for external collaborators to JetBrains products (I've mentioned it in the [README](https://github.com/JetBrains/teamcity-sdk-docs/blob/master/README.md) to this project): we can only accept pull requests from those authors who have signed the [Contributor License Agreement](https://www.jetbrains.com/agreements/cla/).
Could you please sign and send its digital copy to Jetbrains, so we can merge your pull request?
In case you don't want or don't have time to, please let us know, and though I will have to close this PR – I will fix the example in the doc via my direct commit, based on your proposition.
Thanks for your comprehension!

**Comment by pscheit** [comment]
@mkjetbrains signed

**Comment by mkjetbrains** [comment]
Ok, thanks a lot! Checked and ready to merge.

**Pull request merged**
